import SalaryManager from '../ProductList/SalaryManager/SalaryManager'
import Passer from '../ProductList/IntelligentProperty/Passer'
import PaymentProperty from '../ProductList/IntelligentProperty/PaymentProperty'
import AccountManager from '../Public/AccountManagerPublic'
import ProductIntroduce from "../ProductIntroduce/ProductIntroduce"
import CommonCompanyMessage from "./CommonCompanyMessage/CommonCompanyMessage"
import Welfare from "../ProductList/Welfare/Welfare"

export default[
  {
    path:'/CommonCompany',
    name:'indexCompany',
    meta:{
      title:'租客公司'
    },
    redirect:'CommonCompany/index',
    component:resolve => require(['@/pages/CommonCompany/index_company'], resolve),
    children:[
      {
        path:'index',
        component:()=>import('@/pages/CommonCompany/Index/index'),
        meta:{
          title:'首页'
        }
      },
      ...ProductIntroduce,
      {
        path:'CommonCompanyManager',
        meta:{
          title:'公司管理'
        },
        redirect:'CommonCompanyManager/CommonCompanyDepartmentManager',
        component:()=>import('@/pages/CommonCompany/CommonCompanyManager/index'),
        children:[
          {
            path:'CommonCompanyEmployeeManager',
            meta:{
              title:'员工管理'
            },
            redirect:'CommonCompanyEmployeeManager/CommonCompanyEmployeeManager',
            component:()=>import('@/pages/CommonCompany/CommonCompanyManager/CommonCompanyEmployeeManager/index'),
            children:[
              {
                path:'CommonCompanyEmployeeManager',
                meta:{
                  title:'员工管理'
                },
                component:()=>import('@/pages/CommonCompany/CommonCompanyManager/CommonCompanyEmployeeManager/commonCompanyEmployeeManager'),
              },
              {
                path:'importEmployee',
                meta:{
                  title:'导入员工'
                },
                component:()=>import('@/pages/CommonCompany/CommonCompanyManager/CommonCompanyEmployeeManager/importEmployee'),
              }
            ]
          },
          {
            path:'CommonCompanyDepartmentManager',
            meta:{
              title:'部门管理'
            },
            component:()=>import('@/pages/CommonCompany/CommonCompanyManager/commonCompanyDepartmentManager'),
          },
          {
            path:'CommonCompanyPositionManager',
            meta:{
              title:'职位管理'
            },
            component:()=>import('@/pages/CommonCompany/CommonCompanyManager/CommonCompanyPositionManager'),
          },
          {
            path:'CommonCompanyPowerManager',
            meta:{
              title:'权限管理'
            },
            component:()=>import('@/pages/CommonCompany/CommonCompanyManager/CommonCompanyPowerManager'),
          },
          {
            path:'AttendanceManager',
            meta:{
              title:'考勤管理'
            },
            component:()=>import('@/pages/CommonCompany/CommonCompanyManager/AttendanceManager/index'),
            redirect:'AttendanceManager/AttendanceConfig',
            children:[
              {
                path:'AttendanceConfig',
                meta:{
                  title:'考勤配置'
                },
                component:()=>import('@/pages/CommonCompany/CommonCompanyManager/AttendanceManager/AttendanceConfig/index'),
                redirect:'AttendanceConfig/AttendanceConfig',
                children:[
                  {
                    path:'AttendanceConfig',
                    meta:{
                      title:'班制管理'
                    },
                    component:()=>import('@/pages/CommonCompany/CommonCompanyManager/AttendanceManager/AttendanceConfig/attendanceConfig'),
                  },
                  {
                    path:'AttendanceGroup',
                    meta:{
                      title:'考勤组管理'
                    },
                    component:()=>import('@/pages/CommonCompany/CommonCompanyManager/AttendanceManager/AttendanceConfig/attendanceGroup'),
                  }
                ],
              },
              {
                path:'AttendanceStatistics',
                meta:{
                  title:'考勤统计'
                },
                component:()=>import('@/pages/CommonCompany/CommonCompanyManager/AttendanceManager/AttendanceStatistics/index'),
                redirect:'AttendanceStatistics/AttendanceByMonth',
                children:[
                  {
                    path:'AttendanceByMonth',
                    meta:{
                      title:'月考勤'
                    },
                    component:()=>import('@/pages/CommonCompany/CommonCompanyManager/AttendanceManager/AttendanceStatistics/attendanceByMonth'),
                  },
                  {
                    path:'AttendanceByDay',
                    meta:{
                      title:'日考勤'
                    },
                    component:()=>import('@/pages/CommonCompany/CommonCompanyManager/AttendanceManager/AttendanceStatistics/attendanceByDay'),
                  },
                  {
                    path:'AttendanceReset',
                    meta:{
                      title:'重新计算考勤'
                    },
                    component:()=>import('@/pages/CommonCompany/CommonCompanyManager/AttendanceManager/AttendanceStatistics/attendanceReset'),
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        path:'CommonCompanyProduct',
        meta:{
          title:'业务管理'
        },
        component:()=>import('@/pages/CommonCompany/CommonCompanyProduct/index'),
        children:[
          {
            path:'SalaryManager',
            meta:{
              title:'贷发工资'
            },
            component:()=>import('@/pages/CommonCompany/CommonCompanyProduct/SalaryManager/index'),
            redirect:'',
            children:[
              ...SalaryManager
            ]
          },
          {
            path:'IntelligentProperty',
            meta:{
              title:'智慧物业'
            },
            component:()=>import('@/pages/CommonCompany/CommonCompanyProduct/IntelligentProperty/index'),
            children:[
              {
                path:'PaymentProperty',
                meta:{
                  title:'智能缴费'
                },
                redirect:'PaymentProperty/Renter',
                component:()=>import('@/pages/CommonCompany/CommonCompanyProduct/IntelligentProperty/PaymentProperty/index'),
                children:[
                  ...PaymentProperty
                ]
              },
              {
                path:'Passer',
                meta:{
                  title:'通行客'
                },
                component:()=>import('@/pages/CommonCompany/CommonCompanyProduct/IntelligentProperty/Passer/index'),
                redirect:'Passer/Renter',
                children:[
                  ...Passer
                ]
              }
            ]
          },
          {
            path:'Welfare',
            meta:{
              title:'福利社'
            },
            redirect:'Welfare/PayRule',
            component:()=>import('@/pages/ProductList/Welfare/index'),
            children:[
              ...Welfare
            ]
          },
          {
            path:'RepairManager',
            meta:{
              title:'报修管理'
            },
            redirect:'RepairManager/repairManager',
            component:()=>import('@/pages/CommonCompany/repairManager/index'),
            children:[
              {
                path:'repairManager',
                meta:{
                  title:'报修管理'
                },
                component:()=>import('@/pages/CommonCompany/repairManager/repairManager'),
              },
              {
                path:'repairListDetails',
                meta:{
                  title:'报修管理详情'
                },
                component:()=>import('@/pages/CommonCompany/repairManager/repairListDetails'),
              },
            ]
          }
        ]
      },
      ...AccountManager,
      {
        path:'CommonCompanyNotice',
        meta:{
          title:'通知公告'
        },
        redirect:'CommonCompanyNotice/CommonCompanyNoticeList',
        component:()=>import('@/pages/CommonCompany/CommonCompanyNotice/index'),
        children:[
          {
            path:'CommonCompanyNoticeList',
            meta:{
              title:'通知公告列表'
            },
            component:()=>import('@/pages/CommonCompany/CommonCompanyNotice/CommonCompanyNoticeList'),
          },
          {
            path:'CommonCompanyNoticeListjjs',
            meta:{
              title:'通知公告列表'
            },
            component:()=>import('@/pages/CommonCompany/CommonCompanyNotice/CommonCompanyNoticeListjjs'),
          },
          {
            path:'CommonCompanyNoticeDetails',
            meta:{
              title:'通知公告详情'
            },
            component:()=>import('@/pages/CommonCompany/CommonCompanyNotice/CommonCompanyNoticeDetails'),
          },
          {
            path:'CommonCompanyNoticeDetailsjjs',
            meta:{
              title:'通知公告详情'
            },
            component:()=>import('@/pages/CommonCompany/CommonCompanyNotice/CommonCompanyNoticeDetailsjjs'),
          },
        ]
      },
      {
        path:'CommonCompanyCenter',
        meta:{
          title:'企业中心'
        },
        component:()=>import('@/pages/CommonCompany/CommonCompanyCenter/index'),
        children:[
          {
            path:'CommonCompanyInfo',
            meta:{
              title:'企业信息'
            },
            component:()=>import('@/pages/CommonCompany/CommonCompanyCenter/commonCompanyInfo'),
          },
          {
            path:'CommonCompanyInfoEdit',
            meta:{
              title:'编辑企业信息'
            },
            component:()=>import('@/pages/CommonCompany/CommonCompanyCenter/commonCompanyInfoEdit'),
          },
          {
            path:'CommonCompanyMessage',
            meta:{
              title:'消息管理'
            },
            redirect:'CommonCompanyMessage/CommonCompanyMessage',
            component:()=>import('@/pages/CommonCompany/CommonCompanyCenter/commonCompanyMessage'),
            children:[
            ...CommonCompanyMessage
            ]
          },
          {
            path:'CommonCompanyPermissions',
            meta:{
              title:'权限管理'
            },
            component:()=>import('@/pages/CommonCompany/CommonCompanyCenter/commonCompanyPermissions'),
          },
          {
            path:'CommonCompanyInfoSet',
            meta:{
              title:'账户设置'
            },
            component:()=>import('@/pages/CommonCompany/CommonCompanyCenter/commonCompanyInfoSet/index'),
            redirect:'CommonCompanyInfoSet/CommonCompanyChangeMobile',
            children:[
              {
                path:'CommonCompanyChangeMobile',
                meta:{
                  title:'更换手机号'
                },
                component:()=>import('@/pages/CommonCompany/CommonCompanyCenter/commonCompanyInfoSet/CommonCompanyChangeMobile'),
              },
              {
                path:'CommonCompanyChangeManager',
                meta:{
                  title:'更换管理员'
                },
                component:()=>import('@/pages/CommonCompany/CommonCompanyCenter/commonCompanyInfoSet/CommonCompanyChangeManager'),
              },
            ]
          },
           {
            path:'CommonCompanyModifyPassword',
            meta:{
              title:'修改密码'
            },
            component:()=>import('@/pages/CommonCompany/CommonCompanyCenter/CommonCompanyModifyPassword'),
          }
        ]
      },
      {
        path:'CommonCompanyPropertyInfo',
        meta:{
          title:'物业公司信息'
        },
        component:()=>import('@/pages/CommonCompany/CommonCompanyProperty/commonCompanyProperty'),
      },
    ]
  }
]
